/* Generated by x16snd from the kakuro project, target dos-fm (AdLib / Sound Blaster OPL2 (OPL register stream)). Do not edit. */
#ifndef SFX_BANK_H
#define SFX_BANK_H

#define SFX_BANK_FILE "sfx.opl"

#define SFX_CLICK        0x0000  /* 64 bytes, 0.15 s, voices [8] */
#define SFX_SELECT       0x0040  /* 102 bytes, 0.65 s, voices [7, 8] */
#define SFX_BACK         0x00A6  /* 102 bytes, 0.65 s, voices [7, 8] */
#define SFX_PAGE         0x010C  /* 160 bytes, 0.47 s, voices [7, 8] */
#define SFX_PLACE1       0x01AC  /* 62 bytes, 0.47 s, voices [8] */
#define SFX_PLACE2       0x01EA  /* 62 bytes, 0.47 s, voices [8] */
#define SFX_PLACE3       0x0228  /* 62 bytes, 0.47 s, voices [8] */
#define SFX_PLACE4       0x0266  /* 62 bytes, 0.47 s, voices [8] */
#define SFX_PLACE5       0x02A4  /* 62 bytes, 0.47 s, voices [8] */
#define SFX_PLACE6       0x02E2  /* 62 bytes, 0.47 s, voices [8] */
#define SFX_PLACE7       0x0320  /* 62 bytes, 0.47 s, voices [8] */
#define SFX_PLACE8       0x035E  /* 62 bytes, 0.47 s, voices [8] */
#define SFX_PLACE9       0x039C  /* 62 bytes, 0.47 s, voices [8] */
#define SFX_VERIFY_ON    0x03DA  /* 86 bytes, 1.25 s, voices [7, 8] */
#define SFX_VERIFY_OFF   0x0430  /* 86 bytes, 1.25 s, voices [7, 8] */
#define SFX_WRONG        0x0486  /* 92 bytes, 0.43 s, voices [8] */
#define SFX_DIALOG       0x04E2  /* 86 bytes, 2.58 s, voices [7, 8] */
#define SFX_SOLVED       0x0538  /* 340 bytes, 4.55 s, voices [5, 6, 7, 8] */

#define SFX_COUNT 18
#define SFX_BANK_SIZE 1676

#endif
