/* Generated by x16snd from the kakuro project, target dos-midi (General MIDI / MPU-401 (MIDI stream)). Do not edit. */
#ifndef SFX_BANK_H
#define SFX_BANK_H

#define SFX_BANK_FILE "sfx.mds"

#define SFX_CLICK        0x0000  /* 78 bytes, 0.15 s, voices [15] */
#define SFX_SELECT       0x004E  /* 73 bytes, 0.5 s, voices [15] */
#define SFX_BACK         0x0097  /* 73 bytes, 0.5 s, voices [15] */
#define SFX_PAGE         0x00E0  /* 190 bytes, 0.32 s, voices [14, 15] */
#define SFX_PLACE1       0x019E  /* 78 bytes, 0.32 s, voices [15] */
#define SFX_PLACE2       0x01EC  /* 78 bytes, 0.32 s, voices [15] */
#define SFX_PLACE3       0x023A  /* 78 bytes, 0.32 s, voices [15] */
#define SFX_PLACE4       0x0288  /* 78 bytes, 0.32 s, voices [15] */
#define SFX_PLACE5       0x02D6  /* 78 bytes, 0.32 s, voices [15] */
#define SFX_PLACE6       0x0324  /* 78 bytes, 0.32 s, voices [15] */
#define SFX_PLACE7       0x0372  /* 78 bytes, 0.32 s, voices [15] */
#define SFX_PLACE8       0x03C0  /* 78 bytes, 0.32 s, voices [15] */
#define SFX_PLACE9       0x040E  /* 78 bytes, 0.32 s, voices [15] */
#define SFX_VERIFY_ON    0x045C  /* 73 bytes, 0.65 s, voices [15] */
#define SFX_VERIFY_OFF   0x04A5  /* 73 bytes, 0.65 s, voices [15] */
#define SFX_WRONG        0x04EE  /* 109 bytes, 0.43 s, voices [15] */
#define SFX_DIALOG       0x055B  /* 73 bytes, 0.8 s, voices [15] */
#define SFX_SOLVED       0x05A4  /* 259 bytes, 3.67 s, voices [13, 14, 15] */

#define SFX_COUNT 18
#define SFX_BANK_SIZE 1703

#endif
