#!/usr/bin/env python3
"""Prewrap the journal documents at build time; no runtime text files needed."""
from pathlib import Path
import json
import textwrap
ROOT = Path(__file__).resolve().parent.parent


def wrap_document(source, width=60):
    """Join source paragraph lines, preserving headings and separate bullets."""
    lines, paragraph = [], []

    def flush():
        if not paragraph:
            return
        text = ' '.join(paragraph)
        for wrapped in textwrap.wrap(
                text, width=width,
                subsequent_indent='  ' if text.startswith('- ') else '',
                break_long_words=False, break_on_hyphens=False):
            lines.append((wrapped, 0))
        paragraph.clear()

    for raw in source.splitlines():
        line = raw.strip()
        if not line:
            flush()
            lines.append(('', 0))
        elif line.startswith('# '):
            flush()
            lines.extend((part, 1) for part in textwrap.wrap(
                line[2:], width=width, break_long_words=False,
                break_on_hyphens=False))
        else:
            if line.startswith('- '):
                flush()
            paragraph.append(line)
    flush()
    for text, _ in lines:
        if len(text) > width:
            raise ValueError(f'Help word exceeds {width} columns: {text!r}')
        text.encode('ascii')
    return lines


def main():
    output = ['// Generated by tools/generate_documents.py.',
              'struct DocumentLine { char text[61]; unsigned char heading; };']
    for name in ('HELP',):
        lines = wrap_document((ROOT/'assets/documents'/f'{name}.TXT').read_text())
        output.append(f'static const DocumentLine document{name}[] = {{')
        output.extend('    {' + json.dumps(text) + f', {heading}' + '},' for text, heading in lines)
        output.append('};')
        print(f'{name}: {len(lines)} wrapped lines')
    (ROOT/'src/DOCDATA.H').write_text('\n'.join(output)+'\n')


if __name__ == '__main__':
    main()
