#!/usr/bin/env python3
"""Prewrap the journal documents at build time; no runtime text files needed."""
from pathlib import Path
import json
import textwrap
ROOT = Path(__file__).resolve().parent.parent


def main():
    output = ['// Generated by tools/generate_documents.py.',
              'struct DocumentLine { char text[61]; unsigned char heading; };']
    for name in ('HELP',):
        lines = []
        for line in (ROOT/'assets/documents'/f'{name}.TXT').read_text().splitlines():
            heading = line.startswith('# ')
            text = line[2:] if heading else line
            for wrapped in textwrap.wrap(text, width=60, subsequent_indent='  ' if text.startswith('- ') else '',
                                         break_long_words=False, break_on_hyphens=False) or ['']:
                assert len(wrapped) <= 60
                wrapped.encode('ascii')
                lines.append((wrapped, int(heading)))
        output.append(f'static const DocumentLine document{name}[] = {{')
        output.extend('    {' + json.dumps(text) + f', {heading}' + '},' for text, heading in lines)
        output.append('};')
        print(f'{name}: {len(lines)} wrapped lines')
    (ROOT/'src/DOCDATA.H').write_text('\n'.join(output)+'\n')


if __name__ == '__main__':
    main()
