#!/usr/bin/env python3
"""Convert the original ASCII bitmap digit designs into Borland C++ data."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
styles = json.loads((ROOT / "assets/fonts/digits.json").read_text())
assert len(styles) == 5
lines = ["// Generated by tools/generate_fonts.py from assets/fonts/digits.json.",
         "struct DigitSet { int width, height; unsigned char rows[10][11]; };",
         "static const DigitSet digitSets[5] = {"]
for style in styles:
    width, height = style["width"], style["height"]
    assert 1 <= width <= 8 and 1 <= height <= 11
    assert len(style["glyphs"]) == 10
    lines.append("    { %d, %d, { // %s" % (width, height, style["name"]))
    for glyph in style["glyphs"]:
        assert len(glyph) == height
        assert all(len(row) == width and set(row) <= {".", "#"} for row in glyph)
        values = [int(row.replace(".", "0").replace("#", "1"), 2) for row in glyph]
        lines.append("        {" + ",".join("0x%02X" % v for v in values) + "},")
    lines.append("    } },")
lines.append("};")
lines.append("static const char *digitNames[5] = {" +
             ", ".join(json.dumps(s["name"]) for s in styles) + "};")
(ROOT / "src/DIGITDAT.H").write_text("\n".join(lines) + "\n")
