#!/usr/bin/env python3
"""Build the tiny DOS puzzle index without opening every puzzle at startup."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent


def metadata(path):
    rows = []
    source = None
    for line in path.read_text().splitlines():
        text = line.strip()
        if not text:
            continue
        if text.startswith('#') and (len(text) == 1 or not text[1].isdigit()):
            if not rows and not source:
                source = text[1:].strip()
            continue
        cells = text.split()
        if not cells or any(not re.fullmatch(r'(?:[0-9]|#[1-9])', cell) for cell in cells):
            raise ValueError(f'{path}: invalid cell')
        if len(cells) > 15 or (rows and len(cells) != len(rows[0])):
            raise ValueError(f'{path}: invalid board dimensions')
        rows.append(cells)
    if not rows:
        return None  # The corpus has four deliberately empty placeholders.
    if len(rows) > 15:
        raise ValueError(f'{path}: too many rows')
    _, slash, rating_text = (source or '').rpartition('/')
    rating = re.match(r'([1-9])\*', rating_text) if slash else None
    return len(rows), len(rows[0]), int(rating[1]) if rating else 0


def main():
    entries = []
    for identifier in range(1, 101):
        name = f'{identifier:03d}'
        path = ROOT / 'assets/puzzles' / (name + '.puz')
        if not path.exists():
            continue
        info = metadata(path)
        if info:
            entries.append((identifier,) + info)
    if not entries:
        raise ValueError('No playable puzzles')
    lines = ['// Generated by tools/generate_catalog.py; regenerate after editing puzzles.',
             'struct CatalogRecord { unsigned char id, rows, columns, difficulty; };',
             'static const CatalogRecord puzzleCatalog[] = {']
    lines.extend('    {%d, %d, %d, %d},' % item for item in entries)
    lines.extend(['};', 'static const unsigned int puzzleCatalogCount =',
                  '    sizeof(puzzleCatalog) / sizeof(puzzleCatalog[0]);', ''])
    (ROOT / 'src/CATALOG.H').write_text('\n'.join(lines))


if __name__ == '__main__':
    main()
