#!/usr/bin/env python3
"""Bundle the imported chipscore OPL/GM exports without a generator dependency."""
from pathlib import Path
import re
import struct

ROOT = Path(__file__).resolve().parent.parent
SOURCES = ROOT / 'assets/sound'


def main():
    records, payload, tables = [], bytearray(), []
    names = ('MENU', 'GAME', 'GAME2', 'GAME3', 'GAME4', 'SFX')
    # KSN2: six streams per format, offset:u32, length:u16, byte sum:u16.
    count = len(names) * 2
    start = 8 + count * 8
    for folder, extension in [('fm', 'OPL'), ('midi', 'MDS')]:
        header = (SOURCES / folder / 'sfx.h').read_text()
        offsets = [int(value, 16) for value in re.findall(
            r'^#define SFX_\w+\s+(0x[0-9A-F]+)', header, re.M)]
        if len(offsets) != 18 or offsets[0] != 0:
            raise ValueError('Expected the 18 Kakuro effects in generator order')
        bank = (SOURCES / folder / ('SFX.' + extension)).read_bytes()
        tables.append(offsets + [len(bank)])
        for name in names:
            data = (SOURCES / folder / (name + '.' + extension)).read_bytes()
            if not 16 <= len(data) < 32768:
                raise ValueError('Stream must fit a Borland allocation')
            records.append((start + len(payload), len(data), sum(data) & 65535))
            payload.extend(data)
    output = ROOT / 'assets/SOUND.DAT'
    output.write_bytes(b'KSN2' + struct.pack('<HH', count, 0) +
                       b''.join(struct.pack('<IHH', *r) for r in records) + payload)
    lines = ['/* Generated by tools/pack_sound.py. */',
             '#ifndef KAKURO_SNDDATA_H', '#define KAKURO_SNDDATA_H',
             'static const unsigned soundOffsets[2][19] = {']
    lines.extend('    {' + ','.join(str(n) for n in row) + '},' for row in tables)
    lines.extend(['};', '#endif', ''])
    (ROOT / 'src/SNDDATA.H').write_text('\n'.join(lines))
    print(f'Packed {output.name}: {output.stat().st_size:,} bytes')


if __name__ == '__main__':
    main()
